# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('file', models.FileField(default='JSONDoc/None/No-doc.json', upload_to='JSONDoc/')),
                ('upload_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
