# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataservice', '0003_auto_20170116_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('calculated_value', models.CharField(max_length=100)),
                ('calculcated_datetime', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataservice.DataFile')),
            ],
        ),
    ]
