# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservice', '0004_storeddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='key_map',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
